package com.kshavrin.mymoney.navigation

object Destinations {
    const val DECISION = "decision"
    const val SPLASH = "splash"
    const val ONBOARDING = "onboarding"
    const val DASHBOARD = "dashboard"
    const val ADD_EXPENSE = "transaction/expense"
    const val ADD_INCOME = "transaction/income"
    const val TRANSFER = "transaction/transfer"
    const val CURRENCY_RATE = "transaction/currency_rate"
    const val TRANSACTIONS_LIST = "transactions"
    const val TRANSACTION_DETAIL = "transaction_detail"
    const val SEARCH = "search"
    const val SETTINGS = "settings"
    const val SETTINGS_THEME = "settings_theme"
    const val SETTINGS_LANGUAGE = "settings_language"
    const val SETTINGS_ABOUT = "settings_about"
    const val SETTINGS_ABOUT_PRIVACY = "settings_about_privacy"
    const val SETTINGS_ABOUT_HELP = "settings_about_help"
    const val SETTINGS_BACKUP = "settings_backup"
    const val IMPORT_WIZARD = "import_wizard"
    const val CATEGORIES_LIST = "dictionaries/categories"
    const val CATEGORY_EDIT = "dictionaries/categories/edit"
    const val ACCOUNTS_LIST = "dictionaries/accounts"
    const val ACCOUNT_EDIT = "dictionaries/accounts/edit"
    const val FINANCIAL_GOALS = "dictionaries/goals"
    const val FINANCIAL_GOAL_EDIT = "dictionaries/goals/edit"
    const val CURRENCIES_LIST = "dictionaries/currencies"
    const val CURRENCY_EDIT = "dictionaries/currencies/edit"
    const val CLOUD_SYNC = "cloud_sync"
    const val LOCK_SCREEN = "lock_screen"
}
