package com.kshavrin.mymoney.core.common.category

fun categoryIconDominantHex(iconKey: String): String =
    categoryIconDominantHexByKey[iconKey] ?: fallbackCategoryIconHex(iconKey)

private fun fallbackCategoryIconHex(iconKey: String): String =
    fallbackCategoryIconHexes[stableColorIndex(iconKey)]

private fun stableColorIndex(iconKey: String): Int {
    val hash = iconKey.fold(0L) { acc, char -> (acc * 31L + char.code) % Int.MAX_VALUE }
    return (hash % fallbackCategoryIconHexes.size).toInt()
}

private val fallbackCategoryIconHexes =
    listOf(
        "#A9FFE2",
        "#FFE27A",
        "#FF8A80",
        "#FF8FE1",
        "#7FE2FF",
        "#B7FF7A",
        "#C5A3FF",
        "#FFC260",
    )

private val categoryIconDominantHexByKey: Map<String, String> =
    mapOf(
        "ic_cat_clothing" to "#A9FFE2",
        "ic_cat_bills" to "#FF8A80",
        "ic_cat_food" to "#B7FF7A",
        "ic_cat_entertainment" to "#FF8FE1",
        "ic_cat_taxi" to "#FFE27A",
        "ic_cat_housing" to "#7FE2FF",
        "ic_cat_health" to "#FF8A80",
        "ic_cat_pets" to "#FFD060",
        "ic_cat_sport" to "#B7FF7A",
        "ic_cat_gifts" to "#FF8FE1",
        "ic_cat_phone" to "#7FE2FF",
        "ic_cat_transport" to "#7FE2FF",
        "ic_cat_restaurant" to "#FFD060",
        "ic_cat_car" to "#FF8A80",
        "ic_cat_groceries" to "#B7FF7A",
        "ic_cat_coffee" to "#FFD060",
        "ic_cat_books" to "#C5A3FF",
        "ic_cat_rent" to "#7FE2FF",
        "ic_cat_utilities" to "#FFE27A",
        "ic_cat_water" to "#7FE2FF",
        "ic_cat_furniture" to "#B7FF7A",
        "ic_cat_repair" to "#FFC260",
        "ic_cat_pharmacy" to "#FF8A80",
        "ic_cat_dentist" to "#EAF6FF",
        "ic_cat_gym" to "#C5A3FF",
        "ic_cat_beauty" to "#B7FF7A",
        "ic_cat_education" to "#7FE2FF",
        "ic_cat_presentation" to "#FF8FE1",
        "ic_cat_stationery" to "#FFE27A",
        "ic_cat_notebook" to "#B7FF7A",
        "ic_cat_delivery" to "#FF8A80",
        "ic_cat_mail" to "#7FE2FF",
        "ic_cat_cleaning" to "#FF8FE1",
        "ic_cat_laundry" to "#7FE2FF",
        "ic_cat_haircare" to "#C5A3FF",
        "ic_cat_glasses" to "#FFE27A",
        "ic_cat_jewelry" to "#B7FF7A",
        "ic_cat_watch" to "#FF8A80",
        "ic_cat_camera" to "#7FE2FF",
        "ic_cat_electronics" to "#C5A3FF",
        "ic_cat_cloud_upload" to "#7FE2FF",
        "ic_cat_legal" to "#FFE27A",
        "ic_cat_law" to "#FF8A80",
        "ic_cat_moving" to "#7FE2FF",
        "ic_cat_paint" to "#B7FF7A",
        "ic_cat_garden" to "#FF8FE1",
        "ic_cat_art" to "#FFE27A",
        "ic_cat_music" to "#FF8A80",
        "ic_cat_spa" to "#C5A3FF",
        "ic_cat_eco" to "#B7FF7A",
        "ic_cat_baby" to "#7FE2FF",
        "ic_cat_care" to "#FFE27A",
        "ic_cat_party" to "#FF8FE1",
        "ic_cat_security" to "#7FE2FF",
        "ic_cat_cash" to "#B7FF7A",
        "ic_cat_freelance" to "#7FE2FF",
        "ic_cat_investment_growth" to "#FFE27A",
        "ic_cat_currency_exchange" to "#FF8A80",
        "ic_cat_savings" to "#FF8A80",
        "ic_cat_home_key" to "#FFE27A",
        "ic_cat_insurance" to "#7FE2FF",
        "ic_cat_discount" to "#C5A3FF",
        "ic_cat_bank" to "#FFE27A",
        "ic_cat_internet" to "#7FE2FF",
        "ic_cat_streaming" to "#FF8FE1",
        "ic_cat_audio" to "#FF8A80",
        "ic_cat_makeup" to "#FF8FE1",
        "ic_cat_hygiene" to "#C5A3FF",
        "ic_cat_doctor" to "#7FE2FF",
        "ic_cat_kids" to "#FFE27A",
        "ic_cat_games" to "#FFE27A",
        "ic_cat_tickets" to "#FF8A80",
        "ic_cat_flight" to "#7FE2FF",
        "ic_cat_hotel" to "#FFE27A",
        "ic_cat_parking" to "#7FE2FF",
        "ic_cat_fuel" to "#FF8A80",
        "ic_cat_tools" to "#B7FF7A",
        "ic_cat_charity" to "#FF8FE1",
        "ic_cat_credit_card" to "#7FE2FF",
        "ic_cat_tips" to "#FFC260",
        "ic_cat_wallet" to "#B7FF7A",
        "ic_cat_technology" to "#C5A3FF",
    )
