build:
  maxIssues: 0

config:
  validation: true
  warningsAsErrors: false

comments:
  active: true
  AbsentOrWrongFileLicense:
    active: false
  CommentOverPrivateFunction:
    active: false
  CommentOverPrivateProperty:
    active: false
  DeprecatedBlockTag:
    active: false
  EndOfSentenceFormat:
    active: false
  KDocReferencesNonPublicProperty:
    active: false
  OutdatedDocumentation:
    active: false
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
  UndocumentedPublicProperty:
    active: false

complexity:
  active: true
  LongParameterList:
    active: false
  LongMethod:
    active: false
  CyclomaticComplexMethod:
    active: false
  TooManyFunctions:
    active: false
  LargeClass:
    active: false
  ComplexCondition:
    active: false
  NestedBlockDepth:
    active: false

naming:
  active: true
  FunctionNaming:
    active: true
    ignoreAnnotated: [ 'Composable', 'Test' ]
  TopLevelPropertyNaming:
    active: false
  MatchingDeclarationName:
    active: false

style:
  active: true
  MagicNumber:
    active: false
  ReturnCount:
    active: false
  ForbiddenComment:
    active: false
  MaxLineLength:
    active: false
  WildcardImport:
    active: false
  UnusedPrivateMember:
    active: true
    ignoreAnnotated: [ 'Preview' ]
  DataClassContainsFunctions:
    active: false
  UnnecessaryAbstractClass:
    active: false
  ThrowsCount:
    active: false
  LoopWithTooManyJumpStatements:
    active: false

performance:
  active: true
  SpreadOperator:
    active: false

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: false
  InstanceOfCheckForException:
    active: false
