package com.kshavrin.mymoney.core.designsystem.picker

private val CATEGORY_BASE_ICON_KEYS: List<String> =
    listOf(
        "ic_cat_clothing",
        "ic_cat_bills",
        "ic_cat_food",
        "ic_cat_entertainment",
        "ic_cat_taxi",
        "ic_cat_housing",
        "ic_cat_health",
        "ic_cat_pets",
        "ic_cat_sport",
        "ic_cat_gifts",
        "ic_cat_phone",
        "ic_cat_transport",
        "ic_cat_restaurant",
        "ic_cat_car",
        "ic_cat_groceries",
        "ic_cat_coffee",
        "ic_cat_books",
        "ic_cat_rent",
        "ic_cat_utilities",
        "ic_cat_water",
        "ic_cat_furniture",
        "ic_cat_repair",
        "ic_cat_pharmacy",
        "ic_cat_dentist",
        "ic_cat_gym",
        "ic_cat_beauty",
    )

private val CATEGORY_NEW_ICON_KEYS: List<String> =
    listOf(
        "ic_cat_education",
        "ic_cat_presentation",
        "ic_cat_stationery",
        "ic_cat_notebook",
        "ic_cat_delivery",
        "ic_cat_mail",
        "ic_cat_cleaning",
        "ic_cat_laundry",
        "ic_cat_haircare",
        "ic_cat_glasses",
        "ic_cat_jewelry",
        "ic_cat_watch",
        "ic_cat_camera",
        "ic_cat_electronics",
        "ic_cat_cloud_upload",
        "ic_cat_legal",
        "ic_cat_law",
        "ic_cat_moving",
        "ic_cat_paint",
        "ic_cat_garden",
        "ic_cat_art",
        "ic_cat_music",
        "ic_cat_spa",
        "ic_cat_eco",
        "ic_cat_baby",
        "ic_cat_care",
        "ic_cat_party",
        "ic_cat_security",
        "ic_cat_cash",
        "ic_cat_freelance",
        "ic_cat_investment_growth",
        "ic_cat_currency_exchange",
        "ic_cat_savings",
        "ic_cat_home_key",
        "ic_cat_insurance",
        "ic_cat_discount",
        "ic_cat_bank",
        "ic_cat_internet",
        "ic_cat_streaming",
        "ic_cat_audio",
        "ic_cat_makeup",
        "ic_cat_hygiene",
        "ic_cat_doctor",
        "ic_cat_kids",
        "ic_cat_games",
        "ic_cat_tickets",
        "ic_cat_flight",
        "ic_cat_hotel",
        "ic_cat_parking",
        "ic_cat_fuel",
        "ic_cat_tools",
        "ic_cat_charity",
        "ic_cat_credit_card",
        "ic_cat_tips",
        "ic_cat_wallet",
        "ic_cat_technology",
    )

val CATEGORY_REFERENCE_ICON_KEYS: List<String> =
    CATEGORY_BASE_ICON_KEYS + CATEGORY_NEW_ICON_KEYS

val CATEGORY_EXPENSE_ICON_KEYS: List<String> = CATEGORY_REFERENCE_ICON_KEYS

val CATEGORY_INCOME_ICON_KEYS: List<String> = CATEGORY_REFERENCE_ICON_KEYS

/** Default category color swatches offered by [ColorPickerGrid]. */
val CATEGORY_COLOR_PALETTE: List<String> =
    listOf(
        "#9C5BB8",
        "#C9A227",
        "#E07AAE",
        "#F08A3E",
        "#E0A52C",
        "#4A8FCB",
        "#D85A5A",
        "#3DA98A",
        "#7AC29A",
        "#D9A4A4",
        "#9CBBA8",
        "#E07A7A",
        "#3A4F8C",
        "#7A9685",
        "#4A5870",
    )
